# copied from http://github.com/cldwalker/cldwalker.github.com/blob/master/_meta/Thorfile

require 'erb'
require 'fileutils'

class Jekyll < Thor
  method_options  :local=>:boolean, :verbose=>:boolean
  def initialize(*args)
    super
  end
  
  desc "new_post TITLE IS MULTIPLE WORDS", "New blog post"
  method_options :editor=>:boolean, :verbose=>:boolean
  def new_post(*args)
    template_file = '_posts/new_post.md'
    basename = Date.today.to_s + "-#{ args.join('-') }"
    output_file = template_file.sub('new_post', basename)
    title = args.map {|e| e.capitalize}.join(' ')
    result = string_from_template(template_file, :title=>title)
    output_file = create_output_file(output_file, result)
    system(ENV['EDITOR'], output_file) if options['editor']
  end
  
  desc "new_category ONE WORD", "Generate category index and feed pages"
  def new_category(category)
    ['index.html', 'feed.xml'].each do |template|
      template_file = "_categories/#{ template }"
      output_file = "category/#{ category }/#{ template }"
      result = string_from_template template_file, :catname => category
      output_file = create_output_file output_file, result
    end
  end
  
  ################# helpers for dealing with erb
  no_tasks do
    def string_from_template(file, variables)
      variables.each {|k,v| instance_variable_set("@#{k}", v) }
      translated_string = ::ERB.new(File.read(file)).result(binding)
    end
  
    def create_output_file(relative_file, output, local=false)
      destination_dir = options['local'] ? '_site' : root_dir
      FileUtils.mkdir_p(destination_dir)
      destination_file = File.join(destination_dir, relative_file)
      FileUtils.mkdir_p File.dirname(destination_file)
      puts "Created file: #{destination_file}" if options['verbose']
      File.open(destination_file, 'w') {|f| f.write(output) }
      destination_file
    end
  
    def root_dir
      File.expand_path(File.join(File.dirname(__FILE__), '..'))
    end
  end
end